### ISSUE TITLE
Hi, my CPU is 11900K but my motherboard is z590F.

### ISSUE THREAD

**Issue by macrokeven** [luchina-gabriel/EFI-GIGABYTE-Z590M-GAMING-X-11900K-ES-QV1K-RX6900XT#1]
Can you help me to create an EFI to test! Thanks

**Comment by luchina-gabriel** [comment]
This EFI for Z590M Gaming X, it's not a issue.

Please use this repo for create your EFI:
https://github.com/luchina-gabriel/BASE-EFI-INTEL-DESKTOP-11THGEN-ROCKET-LAKE
